language: node_js
node_js:
- '0.10'
before_script:
- gem install sass html-proofer
- npm install -g bower grunt-cli
- npm install
- bower install
script:
- grunt build
after_success:
- grunt deploy
env:
  global:
  - secure: GHo9ZJMLP2CvyuL5OktQINfBzNgFJJar+4t1HSuiPAlgecn1s0pCEFBaYo3Tuw9WGJkbeftFK5V1q7ftUHuXHbehH49eSwI74SSiSY+YEqC/BxBfQIlCvfzjYFrTKzN5G8Jj4IjZ9llAFx2C/CWxMdr61ahFJnX/tywddG1cbZIiVCDNjiu6IuTUu2R/BbyMZSahY6wZYf+YbP83XVy+4Q8mkozzQfel6qL1fpRsJCnyW7emIJwUmp5y0962coD6Gbo7BsvdJllcPa1nJ4J6EUtkZSCpX51xJZafJeh7iLDHpMcqdC5wlih4nO6xC7Mxvk+k1+ddCU6gcEP09K5RsJP4qH3nt+rrKDjL60EzoMTE94v4t0bKinoZm6Z0NsZzpfT0dH69fAOBPZI457Qq9sSn++AZZMyjQfxD/DOS7M7DPnia52RZXUmj6wqw3UojPIECUtjT+06LZkZ6HX9IJQ55y/OXcT1My1j7NyFIh/nrYR8Vdnt2eq6tMcBoUniIyPE8XpPmQZuwk1D85jwRjQY/93DEfKo0TJw989YqHOHy9QIUODGg/k+n9VmgBPf35SfQtMOyBFOHScEcXkQip08EsZyrU/sea/q3E5ytBO82AIVlJy6RkFh7gCoSmg6/SrpC38wkXQwMOQFb0fxvbtyI9u9U5EW8cg/Z8ftU0+o=
  - secure: FAYRCtlm5WcgXDhEFNLX2KKOL65RnsDN0eMm6AEX0o+6X26HylqaZ8xlPzmZ+H9k+rS/x7oYmtDP71f1y3UReC++0T3DN6V7mbHebVKuuq9FDH8I889BTu1K711pQ0D7jZ9pJDjxBwXZgkxigRRIM/8NXM+JV5uMlWbzA+uAY3ljcQMARMvnC5x5Os9RWqSY3Ipv9gZ7IKSciwtOVHr0mPnsE7/F00CU27uPT8tDYiVooPjXQ5n6HEsezyDHjAVlTUp7RWhm4cgjd3t72HvFvsCfEUyoi5GHCNDDu7HWxfmUwG4BpF6yzFKiebgUVWFP7Zh37c5l4jD/kHMdU/hOpq46ymoDLDw852SjsiZJ6XfgY+UdVY63OB1sHsLNtnZswa8Mh84a66uydLUeaUNmmSB4RvmGOz0bZQySDWy49+FBIUzvLC9W9IwIpS5HvlP0Vq83hEKp7UCCz+EbifWvkiBAWZ35Y/yxQCmhF91sDUmrxukBFsjhr5Ycpqa+Miu5O0oDk64DHneTfk1lyXaVZpvg6hj4hcyu4YehbwzoCUWLDj/hrTLumos7euO/ljbL+81v5h9K9EHDdAjslQ5TjA3IgkIKrsCpBbaV0fazg9MtU+HmF+Jj1zB2u8PS9lRMuaPj6JHKrj0R+JQ9LN/eXY5uslt8BI3O5jHT+DBJOq8=
